// Reproduction for issue #3182
//
// The managed agent-tool plugin is generated by
// packages/web/server/lib/agent-tool/runtime.js createToolEntry(). This script
// generates the exact same artifact the runtime writes to
// <dataDir>/agent-tool/openchamber-plugin.js and inspects the resulting tool
// schema. The reported defect: the `action` parameter carries BOTH an `enum`
// and an equivalent `oneOf` of `{const}` branches, which the reporter bisected
// as the trigger for gpt-5.6 streaming failures via Kilo and OpenRouter.
//
// Run from the repository root: bun repro/issue-3182/reproduce.mjs

import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { createAgentToolRuntime } from '../../packages/web/server/lib/agent-tool/runtime.js';

const dataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'issue-3182-'));
const runtime = createAgentToolRuntime({
  crypto,
  fsPromises: fs,
  path,
  dataDir,
  getActivePort: () => 3901,
  executeAction: async () => ({}),
  env: {},
});

await runtime.prepareManagedOpenCodeEnv();
const pluginPath = path.join(dataDir, 'agent-tool', 'openchamber-plugin.js');
const source = await fs.readFile(pluginPath, 'utf8');

const pluginModule = await import(`${pathToFileURL(pluginPath).href}?repro=${Date.now()}`);
const { tool } = await pluginModule.OpenChamberPlugin();

console.log('Generated plugin:', pluginPath);
console.log();

let failures = 0;
for (const [name, entry] of Object.entries(tool)) {
  const action = entry.args.action;
  const hasEnum = Array.isArray(action.enum);
  const hasOneOf = Array.isArray(action.oneOf);
  const enumValues = hasEnum ? action.enum : [];
  const oneOfValues = hasOneOf ? action.oneOf.map((branch) => branch.const) : [];
  const consistent =
    hasEnum && hasOneOf
    && enumValues.length === oneOfValues.length
    && enumValues.every((value, index) => value === oneOfValues[index]);

  console.log(`tool: ${name}`);
  console.log(`  action schema keys: ${Object.keys(action).join(', ')}`);
  console.log(`  enum present:       ${hasEnum} (${enumValues.length} values)`);
  console.log(`  oneOf present:      ${hasOneOf} (${oneOfValues.length} branches)`);
  console.log(`  enum === oneOf:     ${consistent}`);
  console.log();

  if (hasEnum && hasOneOf) {
    failures += 1;
    console.log(`  >>> BUG REPRODUCED: 'action' sets both enum and oneOf, which the`);
    console.log(`  >>> issue reports breaks gpt-5.6 streaming on Kilo/OpenRouter.`);
    console.log();
  }
}

// Also show the raw generated line for the first tool.
const line = source.split('\n').find((text) => text.includes('action: { type: "string"'));
if (line) {
  console.log('Raw generated action line:');
  console.log(line.trim());
  console.log();
}

await fs.rm(dataDir, { recursive: true, force: true });

if (failures > 0) {
  console.log(`RESULT: REPRODUCED (${failures} tool(s) carry both enum and oneOf on action)`);
  process.exit(1);
}
console.log('RESULT: not reproduced');
